
module.exports = {
    topSkills: [
        '.Net Programmers',
        '3ds Max Engineers',
        'Administrative Assistants',
        'Advertising Consultants',
        'AJAX Programmers',
        'Amazon Web Services',
        'Android Programmers',
        'Animators',
        'Article Writers',
        'ASP Programmers',
        'ASP.NET Programmers',
        'Blog Writers',
        'Business Writers',
        'C Programmers',
        'Cocoa Programmers',
        'Content Writers',
        'Copyright Attorneys',
        'Creative Writers',
        'CSS Programmers ',
        'Customer Services Reps',
        'Data Entry Experts',
        'DHTML Programmers',
        'Dot NEt Nuke Programmers',
        'Drupal Programmers',
        'Flash Designers',
        'Foursquare Programmers',
        'French Translators',
        'Google App Engineer',
        'Graphic Designers',
        'HTML Programmers',
        'HTML5 Programmers',
        'Illustrator Designers',
        'InDesign Designers',
        'iPhone Programmers',
        'Java Programmers',
        'JavaScript Programmers',
        'Joomla Programmers',
        'LAMP Programmers',
        'Linux Programmers',
        'Logo Designers',
        'Mac OS Programmers',
        'Magento Programmers',
        'Microsoft Excel Experts ',
        'Microsoft Sharepoing…',
        'Mobile Programmers',
        'MySQL Programmers',
        'Newsletter Writers',
        'Offices Administrators..',
        'Online Writers',
        'Oracle Programmers',
        'osCommerce Programmers',
        'Palm Programmers',
        'PayPal Programmers',
        'Photoshop Designers',
        'PHP Programmers',
        'Ruby on Rails Programmers',
        'Salesforce.com Programmers',
        'SAP Programmers',
        'Sem Consultants',
        'SEO Consultants',
        'Software Testing Programmers',
        'Spanish Translators',
        'SQL Programmers',
        'Transcriptionists'
    ]
}